# Gemfile
# See http://guides.rubygems.org/patterns/#pessimistic_version_constraint

source "https://rubygems.org"

gem 'sass',              '~> 3.4.9'
gem 'compass',           '~> 1.0.1'
gem 'sass-css-importer', '~> 1.0.0.beta.0'
gem 'breakpoint',        '~> 2.5.0'

# "Could not find gem 'singularitygs~> 1.4.0 (>= 0) x64-mingw32' in the gems"
# But without version number declaration, it found and downloaded the latest
# (1.4.0).
# So now this line lacks the version number...
gem 'singularitygs'
