# Gemfile
# See http://guides.rubygems.org/patterns/#pessimistic_version_constraint

source "https://rubygems.org"

gem 'sass',              '3.4.9'
gem 'compass',           '1.0.1'
gem 'sass-css-importer', '1.0.0.beta.0'
gem 'breakpoint',        '2.5.0'
gem 'singularitygs',     '1.6.2'
